version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.7
    commands:
      - apt-get update
      - apt-get install -y jq moreutils
      - jq --version
      - pip install --upgrade boto3==1.14.14 click==7.1.2
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - make synth-all
  post_build:
    commands:
      - cat templateConfiguration.json | jq --arg env $ENVIRONMENT '.Tags.Environment = $env' | sponge templateConfiguration.json
artifacts:
  secondary-artifacts:
    cdkOutput:
      base-directory: $BUILD_DIR
      files:
        - "**/*"
    configOutput:
      files:
        - basicConfiguration.json