version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.7
    commands:
      - apt-get update
      - apt-get install -y jq moreutils
      - jq --version
      - pip install --upgrade boto3
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - make deploy-all