version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npm run cdk synth -- -a bin/cicd-cdk.js -o $BUILD_DIR -c dockerRepository=aws-cicd-docker -c cdkRepository=aws-cicd-cdk -c owner=avanderm -c branch=master -c artifactBucket=antoine.test
artifacts:
  base-directory: $BUILD_DIR
  files:
    - "**/*"